### ISSUE TITLE
websocket support / push on update mechanism?

### ISSUE THREAD

**Issue by waterdrop01** [haskoin/haskoin-store#11]
Hello,
I just discovered haskoin-store, and it looks pretty solid! Congrats on that.
I'm wondering if there is a mechanism to push balance updates (via websocket for instance) from a list of tracked wallet addresses?
If polling at regular interval is the way to go, how much load can it support? (I'm actually just planning to track a dozen of xpub adresses, but I was wondering performance-wise, should I poll every second, every minute...)
Thanks!

**Comment by xenog** [comment]
Hello,

At the moment support for this specific kind of thing is not there yet. There is an events endpoint that will stream server events to the client as they happen. Those events include transactions and blocks. But there is no filtering available at the moment, so you get all transaction and block ids as they are indexed.

I'll add a filtered event endpoint that only reports on incoming transactions affecting an address or xpub. That should end up being useful to you.

Greetings

**Comment by petergombos** [comment]
I would also love to use this feature to monitor address utxos. Is there some documentation on how to integrate with the current events endpoint using websockets?

Thanks

**Comment by jprupp** [comment]
I haven't gotten around to supporting any sort of filtering, but the `/events` endpoint supports WebSocket connections. You can connect to it and it will output events for every transaction and block received on the block chain.

If you have [`websocat`](https://github.com/vi/websocat):
```sh
websocat wss://api.haskoin.com/bch/events
```

If you are running Haskoin Store locally (default parameters):
```sh
websocat ws://127.0.0.1:3000/events
```

**Comment by petergombos** [comment]
Thanks, turns out I was missing the prefix `btc` from the api path 🤦
