### ISSUE TITLE
haskoin-store-0.19.5 build failure

### ISSUE THREAD

**Issue by DanBurton** [haskoin/haskoin-store#12]
As seen on the Stackage build server

```
    /var/stackage/work/unpack-dir/unpacked/haskoin-store-0.19.5-60ae53ad9884fa
25c7e9d9325bc5d54ac575bc1dd5805e4ba554985e64402d5d/src/Network/Haskoin/Store/D
ata.hs:844:32: error:
        • Couldn't match expected type ‘HostAddress’
                      with actual type ‘SockAddr’
        • In the second argument of ‘NetworkAddress’, namely ‘a’
          In the second argument of ‘($)’, namely ‘NetworkAddress s a’
          In a stmt of a 'do' block: put $ NetworkAddress s a
        |
    844 |         put $ NetworkAddress s a
        |                                ^

    /var/stackage/work/unpack-dir/unpacked/haskoin-store-0.19.5-60ae53ad9884fa
25c7e9d9325bc5d54ac575bc1dd5805e4ba554985e64402d5d/src/Network/Haskoin/Store/D
ata.hs:851:34: error:
        • Couldn't match expected type ‘SockAddr’
                      with actual type ‘HostAddress’
        • In the second argument of ‘PeerInformation’, namely ‘a’
          In the second argument of ‘($)’, namely ‘PeerInformation u a v s b’
          In a stmt of a 'do' block: return $ PeerInformation u a v s b
        |
    851 |       return $ PeerInformation u a v s b
        |                                  ^
```

**Comment by jprupp** [comment]
It now depends on the more recent `haskoin-core-0.10.0` which isn't backwards-compatible. I didn't put this information in the `package.yaml` file because I don't like to add dependency version information in two places: `package.yaml` and `stack.yaml`.

**Comment by runeksvendsen** [comment]
IMHO, if a package depends on another package within a specific version (range), it should be added to its package.yaml/.cabal-file. As I view it, the stack.yaml file represents *one* possible dependency configuration, which is known to work, while the package.yaml/.cabal file defines *all possible* dependency configurations that work.

**Comment by jprupp** [comment]
Yes, I know, but it still means putting version information for dependencies in more than one file. I sometimes put low bounds in `package.yaml`. I may start doing it again.

**Comment by jprupp** [comment]
I fixed this in the latest version. There is a lower bound on the version of `haskoin-core` to prevent this from happening. I'll close.
